-- ===============================================================
-- Title: Revenue Analysis Queries
-- Description: Demonstrates SQL queries used to analyze revenue
--              trends, device performance, and transaction insights.
-- ===============================================================


/*
==============================================================
TOTAL REVENUE BY PRODUCT
==============================================================

Calculate revenue generated by each product.
*/

SELECT
    product,
    SUM(amount) AS total_revenue
FROM CustomerTransactions
GROUP BY product
ORDER BY total_revenue DESC;



/*
==============================================================
REVENUE BY DEVICE
==============================================================

Analyze revenue generated from different login devices.
*/

SELECT
    login_device,
    SUM(amount) AS total_revenue
FROM CustomerTransactions
GROUP BY login_device
ORDER BY total_revenue DESC;



/*
==============================================================
REVENUE BY TRANSACTION STATUS
==============================================================

Analyze revenue based on transaction status.
*/

SELECT
    transaction_status,
    SUM(amount) AS revenue
FROM CustomerTransactions
GROUP BY transaction_status;



/*
==============================================================
TOP 5 HIGHEST VALUE TRANSACTIONS
==============================================================

Identify the largest transactions.
*/

SELECT
    customer_name,
    product,
    amount
FROM CustomerTransactions
ORDER BY amount DESC
LIMIT 5;



/*
==============================================================
DEVICE PERFORMANCE ANALYSIS
==============================================================

Find the average revenue generated per device.
*/

SELECT
    login_device,
    AVG(amount) AS avg_revenue
FROM CustomerTransactions
GROUP BY login_device
ORDER BY avg_revenue DESC;
